# Form implementation generated from reading ui file 'ui_ai_manager_chat.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ui_ai_manager_chat(object):
    def setupUi(self, ui_ai_manager_chat):
        ui_ai_manager_chat.setObjectName("ui_ai_manager_chat")
        ui_ai_manager_chat.resize(932, 612)
        self.centralwidget = QtWidgets.QWidget(parent=ui_ai_manager_chat)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(280, 20, 631, 461))
        self.textEdit.setObjectName("textEdit")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 256, 561))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(280, 490, 631, 91))
        self.lineEdit.setObjectName("lineEdit")
        ui_ai_manager_chat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ui_ai_manager_chat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 932, 22))
        self.menubar.setObjectName("menubar")
        ui_ai_manager_chat.setMenuBar(self.menubar)

        self.retranslateUi(ui_ai_manager_chat)
        QtCore.QMetaObject.connectSlotsByName(ui_ai_manager_chat)

    def retranslateUi(self, ui_ai_manager_chat):
        _translate = QtCore.QCoreApplication.translate
        ui_ai_manager_chat.setWindowTitle(_translate("ui_ai_manager_chat", "MainWindow"))
