# Form implementation generated from reading ui file 'win_main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(660, 16, 121, 30))
        self.textEdit.setObjectName("textEdit")
        self.but_bg_moi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_bg_moi.setGeometry(QtCore.QRect(690, 90, 75, 26))
        self.but_bg_moi.setObjectName("but_bg_moi")
        self.but_bg_cu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_bg_cu.setGeometry(QtCore.QRect(690, 132, 75, 26))
        self.but_bg_cu.setObjectName("but_bg_cu")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(690, 176, 75, 26))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(690, 220, 75, 26))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(690, 267, 75, 26))
        self.pushButton_5.setObjectName("pushButton_5")
        self.but_bg_voice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_bg_voice.setGeometry(QtCore.QRect(664, 317, 121, 61))
        self.but_bg_voice.setObjectName("but_bg_voice")
        self.but_stop_bg_voice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_stop_bg_voice.setGeometry(QtCore.QRect(690, 420, 75, 26))
        self.but_stop_bg_voice.setObjectName("but_stop_bg_voice")
        self.text_tb = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_tb.setGeometry(QtCore.QRect(30, 16, 621, 30))
        self.text_tb.setObjectName("text_tb")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 65, 621, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Đăng nhập</p></body></html>"))
        self.but_bg_moi.setText(_translate("MainWindow", "Báo giá mới"))
        self.but_bg_cu.setText(_translate("MainWindow", "Báo giá cũ"))
        self.pushButton_3.setText(_translate("MainWindow", "Thông tin KH"))
        self.pushButton_4.setText(_translate("MainWindow", "Tin đấu thầu"))
        self.pushButton_5.setText(_translate("MainWindow", "Tài liệu"))
        self.but_bg_voice.setText(_translate("MainWindow", "Voice Quotation"))
        self.but_stop_bg_voice.setText(_translate("MainWindow", "......"))
        self.text_tb.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Tìm kiếm ...</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
