# Form implementation generated from reading ui file 'ds_cong_ty.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ViewAllCompany(object):
    def setupUi(self, ViewAllCompany):
        ViewAllCompany.setObjectName("ViewAllCompany")
        ViewAllCompany.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=ViewAllCompany)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 20, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 71, 505, 27))
        self.textEdit.setObjectName("textEdit")
        self.but_search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_search.setGeometry(QtCore.QRect(520, 70, 101, 29))
        self.but_search.setObjectName("but_search")
        self.but_add_company = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_add_company.setGeometry(QtCore.QRect(650, 250, 131, 31))
        self.but_add_company.setObjectName("but_add_company")
        self.but_search_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_search_4.setGeometry(QtCore.QRect(650, 290, 131, 31))
        self.but_search_4.setObjectName("but_search_4")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(640, 560, 151, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(670, 520, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 110, 611, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(-1, -1, 611, 451))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(-1, -1, 611, 451))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")
        self.but_thu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_thu.setGeometry(QtCore.QRect(650, 140, 131, 31))
        self.but_thu.setObjectName("but_thu")
        self.but_chi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_chi.setGeometry(QtCore.QRect(650, 180, 131, 31))
        self.but_chi.setObjectName("but_chi")
        ViewAllCompany.setCentralWidget(self.centralwidget)

        self.retranslateUi(ViewAllCompany)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ViewAllCompany)

    def retranslateUi(self, ViewAllCompany):
        _translate = QtCore.QCoreApplication.translate
        ViewAllCompany.setWindowTitle(_translate("ViewAllCompany", "MainWindow"))
        self.label.setText(_translate("ViewAllCompany", "THÔNG TIN KHÁCH HÀNG"))
        self.textEdit.setPlaceholderText(_translate("ViewAllCompany", "Tìm kiếm bằng tên công ty, địa chỉ hoặc mã số thuế"))
        self.but_search.setText(_translate("ViewAllCompany", "Tìm kiếm"))
        self.but_add_company.setText(_translate("ViewAllCompany", "Thêm khách hàng mới"))
        self.but_search_4.setText(_translate("ViewAllCompany", "...."))
        self.label_4.setText(_translate("ViewAllCompany", "Phần mềm hỗ trợ bán hàng"))
        self.label_3.setText(_translate("ViewAllCompany", "F-Sales"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ViewAllCompany", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ViewAllCompany", "Tab 2"))
        self.but_thu.setText(_translate("ViewAllCompany", "Thu tiền"))
        self.but_chi.setText(_translate("ViewAllCompany", "Chi tiền"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewAllCompany = QtWidgets.QMainWindow()
    ui = Ui_ViewAllCompany()
    ui.setupUi(ViewAllCompany)
    ViewAllCompany.show()
    sys.exit(app.exec())
