# Form implementation generated from reading ui file 'D:\Fsales_PCCC\UI\gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 641)
        MainWindow.setMinimumSize(QtCore.QSize(955, 641))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_root = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_root.setContentsMargins(8, 4, 8, 8)
        self.verticalLayout_root.setObjectName("verticalLayout_root")
        self.horizontalLayout_header1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_header1.setObjectName("horizontalLayout_header1")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(101, 91))
        self.label.setMaximumSize(QtCore.QSize(101, 91))
        self.label.setStyleSheet("border-image: url(:/Logo/Logo PCCC.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_header1.addWidget(self.label)
        self.verticalLayout_header_texts = QtWidgets.QVBoxLayout()
        self.verticalLayout_header_texts.setObjectName("verticalLayout_header_texts")
        self.label_doanh_so = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_doanh_so.setFont(font)
        self.label_doanh_so.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_doanh_so.setObjectName("label_doanh_so")
        self.verticalLayout_header_texts.addWidget(self.label_doanh_so)
        self.label_so_co_hoi = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_so_co_hoi.setFont(font)
        self.label_so_co_hoi.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_so_co_hoi.setObjectName("label_so_co_hoi")
        self.verticalLayout_header_texts.addWidget(self.label_so_co_hoi)
        self.label_noti = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_noti.setText("")
        self.label_noti.setObjectName("label_noti")
        self.verticalLayout_header_texts.addWidget(self.label_noti)
        self.horizontalLayout_header1.addLayout(self.verticalLayout_header_texts)
        self.verticalLayout_login = QtWidgets.QVBoxLayout()
        self.verticalLayout_login.setObjectName("verticalLayout_login")
        self.text_user = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_user.setMinimumSize(QtCore.QSize(121, 31))
        self.text_user.setMaximumSize(QtCore.QSize(121, 31))
        self.text_user.setStyleSheet("background-color: rgb(230, 255, 245);\n"
"border-color: rgb(255, 234, 235);")
        self.text_user.setObjectName("text_user")
        self.verticalLayout_login.addWidget(self.text_user)
        self.text_password = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_password.setMinimumSize(QtCore.QSize(121, 31))
        self.text_password.setMaximumSize(QtCore.QSize(121, 31))
        self.text_password.setStyleSheet("background-color: rgb(255, 234, 235);\n"
"border-color: rgb(230, 255, 245);")
        self.text_password.setObjectName("text_password")
        self.verticalLayout_login.addWidget(self.text_password)
        self.horizontalLayout_header1.addLayout(self.verticalLayout_login)
        self.verticalLayout_root.addLayout(self.horizontalLayout_header1)
        self.horizontalLayout_toolbar = QtWidgets.QHBoxLayout()
        self.horizontalLayout_toolbar.setObjectName("horizontalLayout_toolbar")
        self.tex_search = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.tex_search.setMinimumSize(QtCore.QSize(300, 30))
        self.tex_search.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tex_search.setStyleSheet("border: 2px solid black;\n"
"border-color: rgb(0, 170, 0);")
        self.tex_search.setObjectName("tex_search")
        self.horizontalLayout_toolbar.addWidget(self.tex_search)
        self.combo_user = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_user.setMinimumSize(QtCore.QSize(231, 31))
        self.combo_user.setMaximumSize(QtCore.QSize(231, 31))
        self.combo_user.setObjectName("combo_user")
        self.horizontalLayout_toolbar.addWidget(self.combo_user)
        self.verticalLayout_root.addLayout(self.horizontalLayout_toolbar)
        self.horizontalLayout_body = QtWidgets.QHBoxLayout()
        self.horizontalLayout_body.setSpacing(12)
        self.horizontalLayout_body.setObjectName("horizontalLayout_body")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_body.addWidget(self.tableWidget)
        self.verticalLayout_actions = QtWidgets.QVBoxLayout()
        self.verticalLayout_actions.setObjectName("verticalLayout_actions")
        self.but_mydesk = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_mydesk.setEnabled(True)
        self.but_mydesk.setMinimumSize(QtCore.QSize(115, 31))
        self.but_mydesk.setStyleSheet("QPushButton#but_mydesk {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid black;\n"
"    background-color: rgb(230, 255, 245);\n"
"\n"
"}\n"
"\n"
"QPushButton#but_mydesk:hover {\n"
"    background-color: rgb(255, 234, 235);\n"
"}\n"
"\n"
"QPushButton#but_mydesk:pressed {            \n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"")
        self.but_mydesk.setObjectName("but_mydesk")
        self.verticalLayout_actions.addWidget(self.but_mydesk)
        self.but_co_hoi_moi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_co_hoi_moi.setEnabled(True)
        self.but_co_hoi_moi.setMinimumSize(QtCore.QSize(115, 31))
        self.but_co_hoi_moi.setObjectName("but_co_hoi_moi")
        self.verticalLayout_actions.addWidget(self.but_co_hoi_moi)
        self.but_tao_co_hoi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_tao_co_hoi.setEnabled(True)
        self.but_tao_co_hoi.setMinimumSize(QtCore.QSize(115, 31))
        self.but_tao_co_hoi.setStyleSheet("QPushButton#but_tao_co_hoi {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid black;\n"
"    background-color: rgb(230, 255, 245);\n"
"\n"
"}\n"
"\n"
"QPushButton#but_tao_co_hoi:hover {\n"
"    background-color: rgb(255, 234, 235);\n"
"}\n"
"\n"
"QPushButton#but_tao_co_hoi:pressed {            \n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"")
        self.but_tao_co_hoi.setObjectName("but_tao_co_hoi")
        self.verticalLayout_actions.addWidget(self.but_tao_co_hoi)
        self.but_crm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_crm.setEnabled(True)
        self.but_crm.setMinimumSize(QtCore.QSize(115, 31))
        self.but_crm.setObjectName("but_crm")
        self.verticalLayout_actions.addWidget(self.but_crm)
        self.but_baocao = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_baocao.setEnabled(True)
        self.but_baocao.setMinimumSize(QtCore.QSize(115, 31))
        self.but_baocao.setObjectName("but_baocao")
        self.verticalLayout_actions.addWidget(self.but_baocao)
        self.but_quan_ly_kho = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_quan_ly_kho.setEnabled(True)
        self.but_quan_ly_kho.setMinimumSize(QtCore.QSize(115, 31))
        self.but_quan_ly_kho.setStyleSheet("QPushButton#but_quan_ly_kho {\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 170, 127);\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton#but_quan_ly_kho:hover {\n"
"    background-color: rgb(255, 234, 235);\n"
"}\n"
"\n"
"QPushButton#but_quan_ly_kho:pressed {            \n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"")
        self.but_quan_ly_kho.setObjectName("but_quan_ly_kho")
        self.verticalLayout_actions.addWidget(self.but_quan_ly_kho)
        self.but_sua_bang_gia = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_sua_bang_gia.setEnabled(False)
        self.but_sua_bang_gia.setMinimumSize(QtCore.QSize(115, 31))
        self.but_sua_bang_gia.setObjectName("but_sua_bang_gia")
        self.verticalLayout_actions.addWidget(self.but_sua_bang_gia)
        self.but_logout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_logout.setEnabled(False)
        self.but_logout.setMinimumSize(QtCore.QSize(115, 31))
        self.but_logout.setObjectName("but_logout")
        self.verticalLayout_actions.addWidget(self.but_logout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_actions.addItem(spacerItem)
        self.but_chat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_chat.setMinimumSize(QtCore.QSize(131, 31))
        self.but_chat.setObjectName("but_chat")
        self.verticalLayout_actions.addWidget(self.but_chat)
        self.label_username = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_username.setFont(font)
        self.label_username.setText("")
        self.label_username.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_username.setObjectName("label_username")
        self.verticalLayout_actions.addWidget(self.label_username)
        self.label_version = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_version.setFont(font)
        self.label_version.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_version.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.verticalLayout_actions.addWidget(self.label_version)
        self.horizontalLayout_body.addLayout(self.verticalLayout_actions)
        self.verticalLayout_root.addLayout(self.horizontalLayout_body)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_doanh_so.setText(_translate("MainWindow", "Doanh số:  100.000.000 - Tỉ lệ thành công:  10/100"))
        self.label_so_co_hoi.setText(_translate("MainWindow", "Bạn đã tạo ra 100 cơ hội cho team!"))
        self.text_user.setPlaceholderText(_translate("MainWindow", "username"))
        self.text_password.setPlaceholderText(_translate("MainWindow", "password"))
        self.tex_search.setPlaceholderText(_translate("MainWindow", "Tìm theo số điện thoại, số báo giá, tên KH"))
        self.but_mydesk.setText(_translate("MainWindow", "Việc đang xử lý"))
        self.but_co_hoi_moi.setText(_translate("MainWindow", "Cơ hội MỚI"))
        self.but_tao_co_hoi.setText(_translate("MainWindow", "Tạo cơ hội"))
        self.but_crm.setText(_translate("MainWindow", "CRM"))
        self.but_baocao.setText(_translate("MainWindow", "Reports"))
        self.but_quan_ly_kho.setText(_translate("MainWindow", "Quản lý kho"))
        self.but_sua_bang_gia.setText(_translate("MainWindow", "Sửa bảng giá"))
        self.but_logout.setText(_translate("MainWindow", "Logout"))
        self.but_chat.setText(_translate("MainWindow", "Chat với Anna"))
        self.label_version.setText(_translate("MainWindow", "..."))


import hinhanh_rc
