# Form implementation generated from reading ui file 'UI\gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 641)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_noti = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_noti.setGeometry(QtCore.QRect(140, 50, 741, 31))
        self.label_noti.setText("")
        self.label_noti.setObjectName("label_noti")
        self.label_username = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(820, 505, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_username.setFont(font)
        self.label_username.setText("")
        self.label_username.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_username.setObjectName("label_username")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(2, 135, 791, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.but_mydesk = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_mydesk.setEnabled(True)
        self.but_mydesk.setGeometry(QtCore.QRect(820, 135, 115, 31))
        self.but_mydesk.setStyleSheet("QPushButton#but_mydesk {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid black;\n"
"    background-color: rgb(230, 255, 245);\n"
"\n"
"}\n"
"\n"
"QPushButton#but_mydesk:hover {\n"
"    background-color: rgb(255, 234, 235);\n"
"}\n"
"\n"
"QPushButton#but_mydesk:pressed {            \n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"")
        self.but_mydesk.setObjectName("but_mydesk")
        self.but_co_hoi_moi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_co_hoi_moi.setEnabled(True)
        self.but_co_hoi_moi.setGeometry(QtCore.QRect(820, 175, 115, 31))
        self.but_co_hoi_moi.setObjectName("but_co_hoi_moi")
        self.but_tao_co_hoi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_tao_co_hoi.setEnabled(True)
        self.but_tao_co_hoi.setGeometry(QtCore.QRect(820, 215, 115, 31))
        self.but_tao_co_hoi.setStyleSheet("QPushButton#but_tao_co_hoi {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid black;\n"
"    background-color: rgb(230, 255, 245);\n"
"\n"
"}\n"
"\n"
"QPushButton#but_tao_co_hoi:hover {\n"
"    background-color: rgb(255, 234, 235);\n"
"}\n"
"\n"
"QPushButton#but_tao_co_hoi:pressed {            \n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"")
        self.but_tao_co_hoi.setObjectName("but_tao_co_hoi")
        self.but_crm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_crm.setEnabled(True)
        self.but_crm.setGeometry(QtCore.QRect(820, 255, 115, 31))
        self.but_crm.setObjectName("but_crm")
        self.but_sua_bang_gia = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_sua_bang_gia.setEnabled(False)
        self.but_sua_bang_gia.setGeometry(QtCore.QRect(820, 425, 115, 31))
        self.but_sua_bang_gia.setObjectName("but_sua_bang_gia")
        self.but_tu_van_pccc = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_tu_van_pccc.setEnabled(False)
        self.but_tu_van_pccc.setGeometry(QtCore.QRect(820, 460, 115, 31))
        self.but_tu_van_pccc.setStyleSheet("QPushButton#but_tu_van_pccc {\n"
"    background-color: #0f766e;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton#but_tu_van_pccc:hover {\n"
"    background-color: #0d8a80;\n"
"}\n"
"QPushButton#but_tu_van_pccc:pressed {\n"
"    background-color: #0a5e57;\n"
"}\n"
"QPushButton#but_tu_van_pccc:disabled {\n"
"    background-color: #cbd5e1;\n"
"    color: #64748b;\n"
"}")
        self.but_tu_van_pccc.setObjectName("but_tu_van_pccc")
        self.but_logout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_logout.setEnabled(False)
        self.but_logout.setGeometry(QtCore.QRect(820, 465, 115, 31))
        self.but_logout.setObjectName("but_logout")
        self.label_doanh_so = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_doanh_so.setGeometry(QtCore.QRect(490, 0, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_doanh_so.setFont(font)
        self.label_doanh_so.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_doanh_so.setObjectName("label_doanh_so")
        self.label_so_co_hoi = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_so_co_hoi.setGeometry(QtCore.QRect(570, 20, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_so_co_hoi.setFont(font)
        self.label_so_co_hoi.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_so_co_hoi.setObjectName("label_so_co_hoi")
        self.combo_user = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_user.setGeometry(QtCore.QRect(562, 100, 231, 31))
        self.combo_user.setObjectName("combo_user")
        self.label_version = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_version.setGeometry(QtCore.QRect(820, 580, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_version.setFont(font)
        self.label_version.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_version.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.but_quan_ly_kho = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_quan_ly_kho.setEnabled(True)
        self.but_quan_ly_kho.setGeometry(QtCore.QRect(820, 385, 115, 31))
        self.but_quan_ly_kho.setStyleSheet("QPushButton#but_quan_ly_kho {\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 170, 127);\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton#but_quan_ly_kho:hover {\n"
"    background-color: rgb(255, 234, 235);\n"
"}\n"
"\n"
"QPushButton#but_quan_ly_kho:pressed {            \n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"")
        self.but_quan_ly_kho.setObjectName("but_quan_ly_kho")
        self.text_user = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_user.setGeometry(QtCore.QRect(250, 50, 121, 31))
        self.text_user.setStyleSheet("background-color: rgb(230, 255, 245);\n"
"border-color: rgb(255, 234, 235);")
        self.text_user.setObjectName("text_user")
        self.text_password = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_password.setGeometry(QtCore.QRect(390, 50, 121, 31))
        self.text_password.setStyleSheet("background-color: rgb(255, 234, 235);\n"
"border-color: rgb(230, 255, 245);")
        self.text_password.setObjectName("text_password")
        self.but_baocao = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_baocao.setEnabled(True)
        self.but_baocao.setGeometry(QtCore.QRect(820, 295, 115, 31))
        self.but_baocao.setObjectName("but_baocao")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(2, 0, 101, 91))
        self.label.setStyleSheet("border-image: url(:/Logo/Logo PCCC.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tex_search = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.tex_search.setGeometry(QtCore.QRect(10, 101, 541, 30))
        self.tex_search.setStyleSheet("border: 2px solid black;\n"
"border-color: rgb(0, 170, 0);")
        self.tex_search.setObjectName("tex_search")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.but_mydesk.setText(_translate("MainWindow", "Việc đang xử lý"))
        self.but_co_hoi_moi.setText(_translate("MainWindow", "Cơ hội MỚI"))
        self.but_tao_co_hoi.setText(_translate("MainWindow", "Tạo cơ hội"))
        self.but_crm.setText(_translate("MainWindow", "CRM"))
        self.but_sua_bang_gia.setText(_translate("MainWindow", "Sửa bảng giá"))
        self.but_tu_van_pccc.setText(_translate("MainWindow", "Tư vấn PCCC"))
        self.but_logout.setText(_translate("MainWindow", "Logout"))
        self.label_doanh_so.setText(_translate("MainWindow", "Doanh số:  100.000.000 - Tỉ lệ thành công:  10/100"))
        self.label_so_co_hoi.setText(_translate("MainWindow", "Bạn đã tạo ra 100 cơ hội cho team!"))
        self.label_version.setText(_translate("MainWindow", "..."))
        self.but_quan_ly_kho.setText(_translate("MainWindow", "Quản lý kho"))
        self.text_user.setPlaceholderText(_translate("MainWindow", "username"))
        self.text_password.setPlaceholderText(_translate("MainWindow", "password"))
        self.but_baocao.setText(_translate("MainWindow", "Reports"))
        self.tex_search.setPlaceholderText(_translate("MainWindow", "Tìm theo số điện thoại, số báo giá, tên KH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
