# Form implementation generated from reading ui file 'UI\new_lead.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewLead(object):
    def setupUi(self, NewLead):
        NewLead.setObjectName("NewLead")
        NewLead.resize(872, 600)
        self.centralwidget = QtWidgets.QWidget(parent=NewLead)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(660, 530, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_username = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(640, 10, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.label_noti = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_noti.setGeometry(QtCore.QRect(20, 30, 561, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_noti.setFont(font)
        self.label_noti.setObjectName("label_noti")
        self.txt_ten_khach_hang = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_ten_khach_hang.setGeometry(QtCore.QRect(20, 63, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_ten_khach_hang.setFont(font)
        self.txt_ten_khach_hang.setStyleSheet("border: 1px solid black;\n"
"border-color: rgb(0, 0, 177);")
        self.txt_ten_khach_hang.setObjectName("txt_ten_khach_hang")
        self.txt_so_dt = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_so_dt.setGeometry(QtCore.QRect(280, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_so_dt.setFont(font)
        self.txt_so_dt.setStyleSheet("border: 1px solid black;\n"
"border-color: rgb(0, 0, 177);")
        self.txt_so_dt.setObjectName("txt_so_dt")
        self.txt_ten_cong_ty = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_ten_cong_ty.setGeometry(QtCore.QRect(20, 100, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_ten_cong_ty.setFont(font)
        self.txt_ten_cong_ty.setStyleSheet("border: 1px solid black;\n"
"border-color: rgb(0, 0, 177);")
        self.txt_ten_cong_ty.setObjectName("txt_ten_cong_ty")
        self.txt_email = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_email.setGeometry(QtCore.QRect(440, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_email.setFont(font)
        self.txt_email.setObjectName("txt_email")
        self.txt_mst = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_mst.setGeometry(QtCore.QRect(440, 63, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_mst.setFont(font)
        self.txt_mst.setStyleSheet("border: 1px solid black;\n"
"border-color: rgb(0, 0, 177);")
        self.txt_mst.setObjectName("txt_mst")
        self.txt_yeu_cau = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_yeu_cau.setGeometry(QtCore.QRect(20, 220, 581, 361))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_yeu_cau.setFont(font)
        self.txt_yeu_cau.setStyleSheet("border: 2px solid black;")
        self.txt_yeu_cau.setObjectName("txt_yeu_cau")
        self.but_upload = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_upload.setGeometry(QtCore.QRect(670, 210, 131, 41))
        self.but_upload.setObjectName("but_upload")
        self.but_tao_lead = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_tao_lead.setGeometry(QtCore.QRect(673, 80, 131, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.but_tao_lead.setFont(font)
        self.but_tao_lead.setStyleSheet("QPushButton#but_tao_lead {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid black;\n"
"    background-color: rgb(230, 255, 245);\n"
"\n"
"}\n"
"\n"
"QPushButton#but_tao_lead:hover {\n"
"    background-color: rgb(255, 234, 235);\n"
"}\n"
"\n"
"QPushButton#but_tao_lead:pressed {            \n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"")
        self.but_tao_lead.setObjectName("but_tao_lead")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(650, 140, 181, 22))
        self.comboBox.setObjectName("comboBox")
        self.txt_ten_lead = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_ten_lead.setGeometry(QtCore.QRect(20, 180, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_ten_lead.setFont(font)
        self.txt_ten_lead.setStyleSheet("border: 1px solid black;\n"
"border-color: rgb(0, 0, 177);")
        self.txt_ten_lead.setObjectName("txt_ten_lead")
        self.txt_dia_chi = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_dia_chi.setGeometry(QtCore.QRect(20, 140, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_dia_chi.setFont(font)
        self.txt_dia_chi.setStyleSheet("border: 1px solid black;\n"
"border-color: rgb(0, 0, 177);")
        self.txt_dia_chi.setObjectName("txt_dia_chi")
        self.but_sua_lead = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_sua_lead.setGeometry(QtCore.QRect(670, 80, 131, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.but_sua_lead.setFont(font)
        self.but_sua_lead.setStyleSheet("QPushButton#but_sua_lead {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid black;\n"
"    background-color: rgb(230, 255, 245);\n"
"\n"
"}\n"
"\n"
"QPushButton#but_sua_lead:hover {\n"
"    background-color: rgb(255, 234, 235);\n"
"}\n"
"\n"
"QPushButton#but_sua_lead:pressed {            \n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"")
        self.but_sua_lead.setObjectName("but_sua_lead")
        self.txt_file = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.txt_file.setGeometry(QtCore.QRect(610, 280, 256, 241))
        self.txt_file.setObjectName("txt_file")
        self.but_sua_lead.raise_()
        self.label_3.raise_()
        self.label_username.raise_()
        self.label_noti.raise_()
        self.txt_ten_khach_hang.raise_()
        self.txt_so_dt.raise_()
        self.txt_ten_cong_ty.raise_()
        self.txt_email.raise_()
        self.txt_mst.raise_()
        self.txt_yeu_cau.raise_()
        self.but_upload.raise_()
        self.but_tao_lead.raise_()
        self.comboBox.raise_()
        self.txt_ten_lead.raise_()
        self.txt_dia_chi.raise_()
        self.txt_file.raise_()
        NewLead.setCentralWidget(self.centralwidget)

        self.retranslateUi(NewLead)
        QtCore.QMetaObject.connectSlotsByName(NewLead)

    def retranslateUi(self, NewLead):
        _translate = QtCore.QCoreApplication.translate
        NewLead.setWindowTitle(_translate("NewLead", "Tạo cơ hội kinh doanh mới"))
        self.label_3.setText(_translate("NewLead", "F-Sales"))
        self.label_username.setText(_translate("NewLead", "Username"))
        self.label_noti.setText(_translate("NewLead", "Notification"))
        self.txt_ten_khach_hang.setPlaceholderText(_translate("NewLead", "Tên công ty để làm hợp đồng và xuất hóa đơn"))
        self.txt_so_dt.setPlaceholderText(_translate("NewLead", "Số điện thoại"))
        self.txt_ten_cong_ty.setPlaceholderText(_translate("NewLead", "Tên khách hàng"))
        self.txt_email.setPlaceholderText(_translate("NewLead", "Email"))
        self.txt_mst.setPlaceholderText(_translate("NewLead", "Mã số thuế công ty"))
        self.txt_yeu_cau.setPlaceholderText(_translate("NewLead", "Mô tả yêu cầu của khách hàng, tối thiểu 10 từ."))
        self.but_upload.setText(_translate("NewLead", "Upload File đính kèm"))
        self.but_tao_lead.setText(_translate("NewLead", "Tạo CƠ HỘI"))
        self.txt_ten_lead.setPlaceholderText(_translate("NewLead", "Đặt tên cho cơ hội này ..."))
        self.txt_dia_chi.setPlaceholderText(_translate("NewLead", "Địa chỉ của khách hàng"))
        self.but_sua_lead.setText(_translate("NewLead", "Sửa LEAD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewLead = QtWidgets.QMainWindow()
    ui = Ui_NewLead()
    ui.setupUi(NewLead)
    NewLead.show()
    sys.exit(app.exec())
