# Form implementation generated from reading ui file 'phieu_nhap_kho.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NhapKho(object):
    def setupUi(self, NhapKho):
        NhapKho.setObjectName("NhapKho")
        NhapKho.resize(804, 692)
        self.centralwidget = QtWidgets.QWidget(parent=NhapKho)
        self.centralwidget.setObjectName("centralwidget")
        self.label_user = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_user.setGeometry(QtCore.QRect(683, 5, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_user.setFont(font)
        self.label_user.setObjectName("label_user")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(520, 4, 110, 31))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2024, 5, 29), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2026, 12, 31), QtCore.QTime(23, 59, 59)))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2024, 5, 14), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMinimumDate(QtCore.QDate(2024, 5, 14))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2024, 5, 29))
        self.dateEdit.setObjectName("dateEdit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_noti = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_noti.setGeometry(QtCore.QRect(80, 160, 711, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        self.label_noti.setFont(font)
        self.label_noti.setText("")
        self.label_noti.setObjectName("label_noti")
        self.but_xoadong = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_xoadong.setGeometry(QtCore.QRect(661, 660, 90, 30))
        self.but_xoadong.setObjectName("but_xoadong")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(11, 278, 781, 381))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.but_themdong = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_themdong.setGeometry(QtCore.QRect(551, 660, 90, 30))
        self.but_themdong.setObjectName("but_themdong")
        self.but_load_gia = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_load_gia.setGeometry(QtCore.QRect(600, 230, 101, 30))
        self.but_load_gia.setObjectName("but_load_gia")
        self.group_timkiem = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.group_timkiem.setGeometry(QtCore.QRect(10, 67, 785, 91))
        self.group_timkiem.setStyleSheet("background-color: rgb(224, 235, 234);")
        self.group_timkiem.setTitle("")
        self.group_timkiem.setObjectName("group_timkiem")
        self.but_tonkho = QtWidgets.QPushButton(parent=self.group_timkiem)
        self.but_tonkho.setGeometry(QtCore.QRect(650, 10, 128, 32))
        self.but_tonkho.setObjectName("but_tonkho")
        self.textEdit = QtWidgets.QTextEdit(parent=self.group_timkiem)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 401, 31))
        self.textEdit.setObjectName("textEdit")
        self.but_huy_phieu_NHAP = QtWidgets.QPushButton(parent=self.group_timkiem)
        self.but_huy_phieu_NHAP.setGeometry(QtCore.QRect(430, 53, 90, 32))
        self.but_huy_phieu_NHAP.setObjectName("but_huy_phieu_NHAP")
        self.combo_kho = QtWidgets.QComboBox(parent=self.group_timkiem)
        self.combo_kho.setGeometry(QtCore.QRect(430, 10, 201, 31))
        self.combo_kho.setObjectName("combo_kho")
        self.but_phieumoi = QtWidgets.QPushButton(parent=self.group_timkiem)
        self.but_phieumoi.setGeometry(QtCore.QRect(10, 52, 201, 32))
        self.but_phieumoi.setObjectName("but_phieumoi")
        self.but_tonkho_2 = QtWidgets.QPushButton(parent=self.group_timkiem)
        self.but_tonkho_2.setGeometry(QtCore.QRect(740, 90, 128, 32))
        self.but_tonkho_2.setObjectName("but_tonkho_2")
        self.combo_sophieu = QtWidgets.QComboBox(parent=self.group_timkiem)
        self.combo_sophieu.setGeometry(QtCore.QRect(254, 53, 51, 31))
        self.combo_sophieu.setObjectName("combo_sophieu")
        self.label_so_phieu = QtWidgets.QLabel(parent=self.group_timkiem)
        self.label_so_phieu.setGeometry(QtCore.QRect(232, 53, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_so_phieu.setFont(font)
        self.label_so_phieu.setObjectName("label_so_phieu")
        self.but_save_phieu_NHAP = QtWidgets.QPushButton(parent=self.group_timkiem)
        self.but_save_phieu_NHAP.setGeometry(QtCore.QRect(540, 53, 90, 32))
        self.but_save_phieu_NHAP.setStyleSheet("QPushButton#but_save_phieu_NHAP {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid black;\n"
"    background-color: rgb(230, 255, 245);\n"
"\n"
"}\n"
"\n"
"QPushButton#but_save_phieu_NHAP:hover {\n"
"    background-color: rgb(255, 234, 235);\n"
"}\n"
"\n"
"QPushButton#but_save_phieu_NHAP:pressed {            \n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"")
        self.but_save_phieu_NHAP.setObjectName("but_save_phieu_NHAP")
        self.but_save_NHAP_tu_p_xuat = QtWidgets.QPushButton(parent=self.group_timkiem)
        self.but_save_NHAP_tu_p_xuat.setGeometry(QtCore.QRect(540, 53, 90, 32))
        self.but_save_NHAP_tu_p_xuat.setStyleSheet("QPushButton#but_save_NHAP_tu_p_xuat {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid black;\n"
"    background-color: rgb(230, 255, 245);\n"
"\n"
"}\n"
"\n"
"QPushButton#but_save_NHAP_tu_p_xuat:hover {\n"
"    background-color: rgb(255, 234, 235);\n"
"}\n"
"\n"
"QPushButton#but_save_NHAP_tu_p_xuat:pressed {            \n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"")
        self.but_save_NHAP_tu_p_xuat.setObjectName("but_save_NHAP_tu_p_xuat")
        self.but_tonkho.raise_()
        self.textEdit.raise_()
        self.but_huy_phieu_NHAP.raise_()
        self.combo_kho.raise_()
        self.but_phieumoi.raise_()
        self.but_tonkho_2.raise_()
        self.label_so_phieu.raise_()
        self.combo_sophieu.raise_()
        self.but_save_phieu_NHAP.raise_()
        self.but_save_NHAP_tu_p_xuat.raise_()
        self.but_sp_moi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_sp_moi.setGeometry(QtCore.QRect(660, 120, 128, 32))
        self.but_sp_moi.setObjectName("but_sp_moi")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(40, 190, 161, 20))
        self.checkBox.setObjectName("checkBox")
        self.combo_so_px = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_so_px.setEnabled(False)
        self.combo_so_px.setGeometry(QtCore.QRect(200, 183, 51, 31))
        self.combo_so_px.setObjectName("combo_so_px")
        self.label_thong_tin = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_thong_tin.setGeometry(QtCore.QRect(260, 193, 531, 16))
        self.label_thong_tin.setText("")
        self.label_thong_tin.setObjectName("label_thong_tin")
        self.text_nguyen_nhan = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_nguyen_nhan.setGeometry(QtCore.QRect(40, 220, 451, 41))
        self.text_nguyen_nhan.setObjectName("text_nguyen_nhan")
        self.check_bao_hanh = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.check_bao_hanh.setGeometry(QtCore.QRect(510, 220, 251, 20))
        self.check_bao_hanh.setObjectName("check_bao_hanh")
        self.check_tra_lai = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.check_tra_lai.setGeometry(QtCore.QRect(510, 246, 251, 20))
        self.check_tra_lai.setObjectName("check_tra_lai")
        self.group_timkiem.raise_()
        self.label_user.raise_()
        self.dateEdit.raise_()
        self.label.raise_()
        self.label_noti.raise_()
        self.tableWidget.raise_()
        self.but_themdong.raise_()
        self.but_load_gia.raise_()
        self.but_xoadong.raise_()
        self.but_sp_moi.raise_()
        self.checkBox.raise_()
        self.combo_so_px.raise_()
        self.label_thong_tin.raise_()
        self.text_nguyen_nhan.raise_()
        self.check_bao_hanh.raise_()
        self.check_tra_lai.raise_()
        NhapKho.setCentralWidget(self.centralwidget)

        self.retranslateUi(NhapKho)
        QtCore.QMetaObject.connectSlotsByName(NhapKho)

    def retranslateUi(self, NhapKho):
        _translate = QtCore.QCoreApplication.translate
        NhapKho.setWindowTitle(_translate("NhapKho", "MainWindow"))
        self.label_user.setText(_translate("NhapKho", "Username"))
        self.dateEdit.setDisplayFormat(_translate("NhapKho", "d/M/yyyy"))
        self.label.setText(_translate("NhapKho", "Phiếu nhập kho"))
        self.but_xoadong.setText(_translate("NhapKho", "Xóa dòng"))
        self.but_themdong.setText(_translate("NhapKho", "Thêm dòng"))
        self.but_load_gia.setText(_translate("NhapKho", "Load đơn giá"))
        self.but_tonkho.setText(_translate("NhapKho", "Xem tồn kho"))
        self.textEdit.setPlaceholderText(_translate("NhapKho", "Tìm kiếm "))
        self.but_huy_phieu_NHAP.setText(_translate("NhapKho", "HỦY BỎ"))
        self.but_phieumoi.setText(_translate("NhapKho", "TẠO MỚI PHIẾU NHẬP KHO"))
        self.but_tonkho_2.setText(_translate("NhapKho", "Xem tồn kho"))
        self.label_so_phieu.setText(_translate("NhapKho", "số"))
        self.but_save_phieu_NHAP.setText(_translate("NhapKho", "SAVE"))
        self.but_save_NHAP_tu_p_xuat.setText(_translate("NhapKho", "SAVE"))
        self.but_sp_moi.setText(_translate("NhapKho", "Thêm sản phẩm MỚI"))
        self.checkBox.setText(_translate("NhapKho", "Nhập lại từ phiếu xuất số"))
        self.text_nguyen_nhan.setPlaceholderText(_translate("NhapKho", "Ghi chú nguyên nhân phải nhập lại hàng theo phiếu xuất"))
        self.check_bao_hanh.setText(_translate("NhapKho", "Nhập lại để bảo hành sửa chữa"))
        self.check_tra_lai.setText(_translate("NhapKho", "Khách trả lại hàng - không mua nữa"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NhapKho = QtWidgets.QMainWindow()
    ui = Ui_NhapKho()
    ui.setupUi(NhapKho)
    NhapKho.show()
    sys.exit(app.exec())
