# Form implementation generated from reading ui file 'quotation_update.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ListBaoGia(object):
    def setupUi(self, ListBaoGia):
        ListBaoGia.setObjectName("ListBaoGia")
        ListBaoGia.resize(723, 392)
        self.centralwidget = QtWidgets.QWidget(parent=ListBaoGia)
        self.centralwidget.setObjectName("centralwidget")
        self.label_header = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_header.setGeometry(QtCore.QRect(130, 10, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_header.setFont(font)
        self.label_header.setObjectName("label_header")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 701, 221))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.but_new_quotation = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_new_quotation.setGeometry(QtCore.QRect(550, 20, 131, 31))
        self.but_new_quotation.setObjectName("but_new_quotation")
        self.label_footer = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_footer.setGeometry(QtCore.QRect(30, 320, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_footer.setFont(font)
        self.label_footer.setObjectName("label_footer")
        ListBaoGia.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ListBaoGia)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 723, 21))
        self.menubar.setObjectName("menubar")
        ListBaoGia.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ListBaoGia)
        self.statusbar.setObjectName("statusbar")
        ListBaoGia.setStatusBar(self.statusbar)

        self.retranslateUi(ListBaoGia)
        QtCore.QMetaObject.connectSlotsByName(ListBaoGia)

    def retranslateUi(self, ListBaoGia):
        _translate = QtCore.QCoreApplication.translate
        ListBaoGia.setWindowTitle(_translate("ListBaoGia", "MainWindow"))
        self.label_header.setText(_translate("ListBaoGia", "DANH SÁCH BÁO GIÁ - LEAD SỐ ..."))
        self.but_new_quotation.setText(_translate("ListBaoGia", "Tạo thêm báo giá mới"))
        self.label_footer.setText(_translate("ListBaoGia", "F-Sales"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ListBaoGia = QtWidgets.QMainWindow()
    ui = Ui_ListBaoGia()
    ui.setupUi(ListBaoGia)
    ListBaoGia.show()
    sys.exit(app.exec())
