# Form implementation generated from reading ui file 'sua_bang_gia.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Bang_gia(object):
    def setupUi(self, Bang_gia):
        Bang_gia.setObjectName("Bang_gia")
        Bang_gia.resize(1244, 645)
        self.centralwidget = QtWidgets.QWidget(parent=Bang_gia)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 30, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(6, 160, 1231, 441))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_noti = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_noti.setGeometry(QtCore.QRect(700, 126, 531, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.label_noti.setFont(font)
        self.label_noti.setText("")
        self.label_noti.setObjectName("label_noti")
        self.but_themdong = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_themdong.setGeometry(QtCore.QRect(1060, 610, 75, 23))
        self.but_themdong.setObjectName("but_themdong")
        self.but_xoadong = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_xoadong.setGeometry(QtCore.QRect(1150, 610, 75, 23))
        self.but_xoadong.setObjectName("but_xoadong")
        self.text_search = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.text_search.setGeometry(QtCore.QRect(140, 120, 541, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_search.setFont(font)
        self.text_search.setObjectName("text_search")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.but_excel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_excel.setGeometry(QtCore.QRect(1080, 60, 101, 31))
        self.but_excel.setObjectName("but_excel")
        Bang_gia.setCentralWidget(self.centralwidget)

        self.retranslateUi(Bang_gia)
        QtCore.QMetaObject.connectSlotsByName(Bang_gia)

    def retranslateUi(self, Bang_gia):
        _translate = QtCore.QCoreApplication.translate
        Bang_gia.setWindowTitle(_translate("Bang_gia", "Quản trị"))
        self.label.setText(_translate("Bang_gia", "Bảng giá hàng hóa thiết bị"))
        self.but_themdong.setText(_translate("Bang_gia", "Thêm dòng"))
        self.but_xoadong.setText(_translate("Bang_gia", "Xóa dòng"))
        self.label_2.setText(_translate("Bang_gia", "Tìm kiếm"))
        self.but_excel.setText(_translate("Bang_gia", "Xuất ra Excel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bang_gia = QtWidgets.QMainWindow()
    ui = Ui_Bang_gia()
    ui.setupUi(Bang_gia)
    Bang_gia.show()
    sys.exit(app.exec())
